name: flutter_auth_flow_example
description: Example app for flutter_auth_flow.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_auth_flow:
    path: ../

flutter:
  uses-material-design: true
