name: flutter_auth_flow
description: >
  A single, fully customizable Flutter widget that handles Sign In, Sign Up,
  and Forgot Password — no routing, no multiple pages, just drop it in.
version: 0.0.2
homepage: https://github.com/maheshbvv/flutter_auth_flow
repository: https://github.com/maheshbvv/flutter_auth_flow
publish_to: https://pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
